default:
  tags:
    - nomad_cluster

stages:
  - build
  - upload
  - release

variables:
  BINARY: "cloud-guardian"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${BINARY}"

build:
  stage: build
  image: docker.io/golang:1.24-alpine
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - apk add --no-cache git make zip tar
    - go mod download
    - VERSION=${CI_COMMIT_TAG} make release
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_linux_amd64.tar.gz ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_linux_amd64.tar.gz
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_linux_arm64.tar.gz ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_linux_arm64.tar.gz
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_darwin_amd64.zip ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_darwin_amd64.zip
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_darwin_arm64.zip ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_darwin_arm64.zip
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_windows_amd64.zip ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_windows_amd64.zip
       curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/${BINARY}_${CI_COMMIT_TAG}_windows_arm64.zip ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_windows_arm64.zip

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: ${BINARY} - Linux x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_linux_amd64.tar.gz"
        - name: ${BINARY} - Linux ARM64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_linux_arm64.tar.gz"
        - name: ${BINARY} - macOS x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_darwin_amd64.zip"
        - name: ${BINARY} - macOS ARM64 
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_darwin_arm64.zip"
        - name: ${BINARY} - Windows x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_windows_amd64.zip"
        - name: ${BINARY} - Windows ARM64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}/${BINARY}_${CI_COMMIT_TAG}_windows_arm64.zip"
