default:
  tags:
    - nomad_cluster

stages:
  - build
  - upload
  - release

variables:
  BINARY: "cloud-guardian"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${BINARY}"

build:
  stage: build
  image: docker.io/golang:1.24-alpine
  script:
    - apk add --no-cache git
    - go mod download
    - GOOS=linux GOARCH=amd64 go build -o bin/linux_amd64/${BINARY}
    - GOOS=darwin GOARCH=amd64 go build -o bin/darwin_amd64/${BINARY}
    - GOOS=darwin GOARCH=arm64 go build -o bin/darwin_arm64/${BINARY}
    - GOOS=windows GOARCH=amd64 go build -o bin/windows_amd64/${BINARY}.exe
  artifacts:
    paths:
      - bin/
    expire_in: 1 week

upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/linux_amd64/${BINARY} ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-linux_amd64/${BINARY}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/darwin_amd64/${BINARY} ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-darwin_amd64/${BINARY}
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/darwin_arm64/${BINARY} ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-darwin_arm64/${BINARY}
    - | 
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/windows_amd64/${BINARY}.exe ${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-windows_amd64/${BINARY}.exe


release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: ${BINARY} - Linux x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-linux_amd64/${BINARY}"
          direct_asset_path: "/linux_amd64/${BINARY}"
        - name: ${BINARY} - MacOS x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-darwin_amd64/${BINARY}"
          direct_asset_path: "/darwin_amd64/${BINARY}"
        - name: ${BINARY} - MacOS arm64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-darwin_arm64/${BINARY}"
          direct_asset_path: "/darwin_arm64/${BINARY}"
        - name: ${BINARY} - Windows x64
          url: "${PACKAGE_REGISTRY_URL}/${CI_COMMIT_TAG}-windows_amd64/${BINARY}.exe"
          direct_asset_path: "/windows_amd64/${BINARY}.exe"
